# Site settings
title: Mon site
email: contact@efficiencesoftware.fr
description: > # this means to ignore newlines until "baseurl:"
  Jekyll starter.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sanimation.github.io/jekyll-starter/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

sass:
    sass_dir: _sass

exclude:
  - CHANGELOG.md
  - LICENSE.txt
  - README.md
  - VERSION
  - Gemfile.lock
  - Gemfile
  - Guardfile
  - Rakefile
  - bower.json
  - bower_components
  - node_modules
  - vendor
  - _builds
  - wercker.yml
  - _steps
