---
title: The World of Static Web App
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@efficiencesoftware.fr
description: |
  Jekyll starter.
baseurl: "/jekyll-starter"
url: http://sanimation.github.io/jekyll-starter/
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
exclude:
- CHANGELOG.md
- LICENSE.txt
- README.md
- VERSION
- Gemfile.lock
- Gemfile
- Guardfile
- Rakefile
- bower.json
- bower_components
- node_modules
- vendor
- _builds
- wercker.yml
- _steps
